name: on_pull_request
on:
  pull_request
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: cd build && npx --yes antora local-preview-site.yml
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"
          expires: 2d
          projectId: nativescript-docs-26174
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
